"""initial schema

Revision ID: e7b8f044a33e
Revises: 
Create Date: 2026-08-04 17:17:23.596998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b8f044a33e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_cache',
    sa.Column('barcode', sa.String(length=32), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('MANGA', 'BOOK', 'COMIC_BOOK', 'GRAPHIC_NOVEL', 'VIDEO_GAME', 'BLU_RAY', 'DVD', 'VHS', 'VCD', 'LASERDISC', 'CD', 'VINYL', 'CASSETTE', name='mediatype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('format', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('cover_image_url', sa.String(length=1000), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('SCANNED', 'MANUAL', name='itemsource', native_enum=False, length=10), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_items_barcode'), 'media_items', ['barcode'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_media_items_barcode'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('barcode_cache')
    # ### end Alembic commands ###
